name: Monday Informationals

on:
  schedule:
    - cron: '0 14 * * MON'

jobs:
  monday-informationals:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install Dependencies
        run: npm install --global @artsy/cli@alpha

      - name: Run CLI
        id: cli
        run: |
          echo "::set-output name=standup::$(artsy scheduled:standup-reminder)"
          echo "::set-output name=rfcs::$(artsy scheduled:rfcs)"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          OPSGENIE_API_KEY: ${{ secrets.OPSGENIE_API_KEY }}
          SLACK_WEB_API_TOKEN: ${{ secrets.SLACK_WEB_API_TOKEN }}

      - name: Standup Reminder > Slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            ${{steps.cli.outputs.standup}}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Open RFCs > Slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            ${{steps.cli.outputs.rfcs}}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}